Fix `error: freescout cannot be found in pkgs`
If you try to use the nixos module from this flake without applying the
overlay to your package set, then you'll get an evaluation error like
this:

```
… while evaluating the option `system.build.toplevel':

… while evaluating definitions from `/nix/store/56pw9jd48a07sp5rfamh2rflfx82js82-source/nixos/modules/system/activation/top-level.nix':

… while evaluating the option `warnings':

… while evaluating definitions from `/nix/store/56pw9jd48a07sp5rfamh2rflfx82js82-source/nixos/modules/system/boot/systemd.nix':

… while evaluating the option `systemd.services.freescout-setup.serviceConfig':

… while evaluating definitions from `/nix/store/56pw9jd48a07sp5rfamh2rflfx82js82-source/nixos/modules/system/boot/systemd.nix':

… while evaluating the option `systemd.services.freescout-setup.script':

… while evaluating definitions from `/nix/store/7c30xhz4z7b2kvz8yfgqa9p8ggdgc7hn-source/non-critical-infra/modules/mailserver/freescout.nix':

… while evaluating the option `services.freescout.package':

(stack trace truncated; use '--show-trace' to show the full, detailed trace)

error: expected a string but found a set: { type = "derivation"; __ignoreNulls = true; __structuredAttrs = false; all = «thunk»; args = «thunk»; buildInputs = «thunk»; builder = «thunk»; cmakeFlags = «thunk»; configureFlags = «thunk»; depsBuildBuild = «thunk»; «39 attributes elided» }
at /nix/store/56pw9jd48a07sp5rfamh2rflfx82js82-source/lib/attrsets.nix:106:24:
  105|               in
  106|               if s ? ${attr} then attrByPath' (n + 1) s.${attr} else default
     |                        ^
  107|             )
```

Rather than asking people to apply the overlay (which would require us
to create docs, and would and potentially force our users pay the
cost of instantiating nixpkgs an additional time), let's just make
things work out of the box.